worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }
http {
  access_log /dev/stdout;
  server {
    listen 8080;
    server_name _;

    location = /health {
      proxy_pass http://127.0.0.1:8000/health;
    }

    location /_vless {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_pass http://127.0.0.1:10000;
    }

    location / {
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass http://127.0.0.1:8000;
    }
  }
}
